<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Russert -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
	<title><?=$source->name;?></title>
	<link><?=$source->link;?></link>
	<description><?=$source->description;?></description>
	<lastBuildDate><?=date("r");?></lastBuildDate>
	<atom:link href="http://rss.tulikukka.com/<?=$source->name . ".xml";?>" rel="self" type="application/rss+xml" />
<?php foreach ($items as $item):?>
		<item>
			<title><?=$item['title']?></title>
			<link><?=$item['link']?></link>
			<description>
				<![CDATA[
				<?php if ($item['image']):?>
				<img src="<?=$item['image'];?>" alt="" />
				<?php endif;?>
				<?php if (!empty($item['description'])):?>
					<p><?=$item['description'];?></p>
				<?php endif;?>
				]]>
			</description>
			<?php if ($item['image']):?>
			<?php endif;?>
			<pubDate><?=date("r", $item['seen']->sec);?></pubDate>
			<guid><?=$item['guid'];?></guid>
		</item>
<?php endforeach;?>
</channel>
</rss>

